server:
  port: 8083
spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: caller
          uri: "http://localhost:8082/messages"
          predicates:
            Path=/messages/**
        - id: callme
          uri: "http://localhost:8040/callme"
          predicates:
            Path=/callme/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.thstecnologia.io/realms/GatewayTeste