server:
  port: 8083
spring:
  application.name: api-gateway
  cloud:
    gateway:
      routes:
        - id: callme
          uri: "http://localhost:8040/api/callme"
          predicates:
            Path=/api/callme/**


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.thstecnologia.io/realms/GatewayTeste