server:
  port: 8082
spring:
  application:
    name: caller-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://keycloak.thstecnologia.io/realms/GatewayTeste"