server:
  port: 8040
spring:
  application:
    name: Callme
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak.thstecnologia.io/realms/GatewayTeste/protocol/openid-connect/certs
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
